### PR TITLE
Setup information and update HMMER version

### LINKED ISSUE #187: better status reporting when running setup.py
when running setup.py it's be good to output some messages to show what's going on.

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
Fix #187.

### CODE REVIEW

**Comment by childers** [comment]
Testing now

**Comment by childers** [comment]
$ python manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.

System check identified 1 issue (0 silenced).

You have 5 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): axes, blast, sites.
Run 'python manage.py migrate' to apply them.

August 03, 2018 - 17:08:45
Django version 1.11.15, using settings 'i5k.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

**Comment by childers** [comment]
This is the error text when I run migrate
``` shell
$ python manage.py migrate
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
Operations to perform:
  Apply all migrations: admin, app, auth, axes, blast, clustal, contenttypes, hmmer, sessions, sites
Running migrations:
  Applying axes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
    schema_editor.create_model(model)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 319, in create_model
    self.execute(sql, params or None)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "axes_accessattempt" already exists


```

**Comment by hsiaoyi0504** [comment]
@childers When checking out to other branch, we always need to check if you need to run migrate. I suspect your database is corrupted through the time ... we can take this a look next week.

**Comment by hsiaoyi0504** [comment]
Related discussion is here: https://github.com/jazzband/django-axes/issues/143.

**Comment by childers** [comment]
Thanks for the advice! This fixed the migration issue. continuing testing.

**Pull request merged**
