### PR TITLE
add makeblastdb argument in blast/models.py

### PR DESCRIPTION
**Pull request by deming7h777**

### CODE REVIEW

**Comment by hsiaoyi0504** [comment]
I am curious about this. It seems to me that we intentionally wanted to comment it out before. I don’t the exact reason, though. See this commit: https://github.com/NAL-i5K/genomics-workspace/commit/ec58f840a4bd571d7f5b78a2852469c452aafdec

**Comment by deming7h777** [comment]
> I am curious about this. It seems to me that we intentionally wanted to comment it out before. I don’t the exact reason, though. See this commit: [ec58f84](https://github.com/NAL-i5K/genomics-workspace/commit/ec58f840a4bd571d7f5b78a2852469c452aafdec)

We want to add this argument due to the "fasta-viewer" change.
We want to use "blastdbcmd" which is the tool of NCBI to render the fasta sequence instead of using api,   
in order to make it works the -parse_seqids is necessary

**Comment by childers** [comment]
@hsiaoyi0504 Good to hear from you!  All this started from me getting warning messages that the sequences table was getting close to 1GB, causing some queries to be much slower.  This led us to start looking at other ways we could get to the subject fasta sequences without needing the sequences table.

**Comment by g8tor** [comment]
Closed because this has been folded into g8tor/upgrades branch

**Pull request closed without merging**
