### PR TITLE
Test for blastdb

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
- One test case for blastdb functions
- One test case for manipulating blast admin

### CODE REVIEW

**Comment by childers** [comment]
This was the result when I tried to run the test:

```shell
$ python manage.py test blast.tests
/Users/cchilders/git-repositories/genomics-workspace/suit/admin.py:5: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

Creating test database for alias 'default'...
Got an error creating the test database: database "test_django" already exists

Type 'yes' if you would like to try deleting the test database 'test_django', or 'no' to cancel: yes
Destroying old test database 'default'...
../Users/cchilders/git-repositories/genomics-workspace/webapollo_sso/models.py:4: RemovedInDjango19Warning: Model class webapollo_sso.models.PermsRequest doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class PermsRequest(models.Model):

/Users/cchilders/git-repositories/genomics-workspace/webapollo_sso/models.py:19: RemovedInDjango19Warning: Model class webapollo_sso.models.UserMapping doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class UserMapping(models.Model):

/Users/cchilders/git-repositories/genomics-workspace/drupal_sso/models.py:5: RemovedInDjango19Warning: Model class drupal_sso.models.DrupalUserMapping doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class DrupalUserMapping(models.Model):

/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/templatetags/future.py:25: RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  RemovedInDjango19Warning)

E
======================================================================
ERROR: test_setup_is_shown (blast.tests.BlastAdminTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/test/utils.py", line 196, in inner
    return test_func(*args, **kwargs)
  File "/Users/cchilders/git-repositories/genomics-workspace/blast/tests.py", line 166, in test_setup_is_shown
    wait.until(EC.element_to_be_clickable((By.ID, 'test')))
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 


----------------------------------------------------------------------
Ran 3 tests in 11.314s

FAILED (errors=1)
Destroying test database for alias 'default'...

```

**Comment by hsiaoyi0504** [comment]
@childers Can you modify the 94th line of `blast/tests.py`
from ` wait = WebDriverWait(self.driver, 2)`
to ` wait = WebDriverWait(self.driver, 5)`
and check if it still has issue?

**Comment by childers** [comment]
@hsiaoyi0504 Can you resolve the conflicts, and push back to your branch?

**Comment by childers** [comment]
It looks like we have different errors now:

```shell
$ python manage.py test blast.tests
/Users/cchilders/git-repositories/genomics-workspace/suit/admin.py:5: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

Creating test database for alias 'default'...
../Users/cchilders/git-repositories/genomics-workspace/webapollo_sso/models.py:4: RemovedInDjango19Warning: Model class webapollo_sso.models.PermsRequest doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class PermsRequest(models.Model):

/Users/cchilders/git-repositories/genomics-workspace/webapollo_sso/models.py:19: RemovedInDjango19Warning: Model class webapollo_sso.models.UserMapping doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class UserMapping(models.Model):

/Users/cchilders/git-repositories/genomics-workspace/drupal_sso/models.py:5: RemovedInDjango19Warning: Model class drupal_sso.models.DrupalUserMapping doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class DrupalUserMapping(models.Model):

/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/templatetags/future.py:25: RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  RemovedInDjango19Warning)

E
======================================================================
ERROR: test_setup_is_shown (blast.tests.BlastAdminTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/django/test/utils.py", line 196, in inner
    return test_func(*args, **kwargs)
  File "/Users/cchilders/git-repositories/genomics-workspace/blast/tests.py", line 166, in test_setup_is_shown
    wait.until(EC.element_to_be_clickable((By.ID, 'test')))
  File "/Users/cchilders/git-repositories/genomics-workspace/virtualenv/py2.7/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 


----------------------------------------------------------------------
Ran 3 tests in 22.346s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by hsiaoyi0504** [comment]
@childers I already fixed this and rebase to master. I finally found that the problem is that by default the test server will run in `DEBUG=False` mode. I just overwrite it in the test case.

**Pull request merged**
