### PR TITLE
jQuery3.3.1

### PR DESCRIPTION
**Pull request by deming7h777**

### CODE REVIEW

**Comment by childers** [comment]
@hsiaoyi0504 If you have some time, would you mind reviewing this again? If not, no problem at all.

**Comment by hsiaoyi0504** [comment]
@childers I will review this.

**Comment by hsiaoyi0504** [comment]
@deming7h777 May I check first ? As I remember, you mention that you use jquery-migrate earlier, but it's not included in this pull request. Is it normal ?

**Comment by hsiaoyi0504** [comment]
The console shows that jQuery isn't correctly loaded. @deming7h777 Please update this pull request.
image

**Comment by deming7h777** [comment]
> @deming7h777 May I check first ? As I remember, you mention that you use jquery-migrate earlier, but it's not included in this pull request. Is it normal ?

yes it is. 
At first I used the jquery-migration plugin to update our version but then there were a lot of comprehensive errors, I decided to go step by step again and found out that I can directly update to 3.3.1 via package.json.

**Comment by deming7h777** [comment]
> The console shows that jQuery isn't correctly loaded. @deming7h777 Please update this pull request.
> image

what did you do to show up this error ?
I've never seen it while I was testing

**Comment by deming7h777** [comment]
OK, I changed the code in blast-multi.js from ``` $( window ).unload(function() ``` to ```  <script type='text/javascript'> $(window).on('beforeunload', function(){ console.log("beforeUnload event!"); }); </script>``` to solve the problem

**Comment by hsiaoyi0504** [comment]
@deming7h777 Are you sure this is the solution of previous problem ? It's nonsense to write html syntax in a js file ...

**Comment by hsiaoyi0504** [comment]
image

**Comment by hsiaoyi0504** [comment]
The CI also fails.

**Comment by hsiaoyi0504** [comment]
**hmmer-multi.js** also uses this function, so you need to update it as well.

https://github.com/NAL-i5K/genomics-workspace/blob/a65d7acd1f93062af89baad2f5cea6bf39e893ac/hmmer/static/hmmer/scripts/hmmer-multi.js#L643

**Comment by hsiaoyi0504** [comment]
Looks good to me now.

**Pull request merged**
