### PR TITLE
Add  front-end package management through npm

### PR DESCRIPTION
**Pull request by hsiaoyi0504**

### CODE REVIEW

**Comment by hsiaoyi0504** [comment]
Finished rebase for #151.

**Comment by childers** [comment]
@hsiaoyi0504 will wait until the codebeat test finishes

**Comment by hsiaoyi0504** [comment]
@childers I think it would take forever. Sometimes codebeat will just keep pending and don't start.

**Comment by childers** [comment]
Roger that. Proceeding

**Pull request merged**
