### PR TITLE
remove old virtualenv folder

### PR DESCRIPTION
**Pull request by hsiaoyi0504**

### CODE REVIEW

**Comment by hsiaoyi0504** [comment]
I need to re-consider this

**Comment by hsiaoyi0504** [comment]
I think we can make this pull request as a transition effort to migrate to python3.
Through this pull request, we can review the whole settings related to apache server and celery deamon. 
I would like to rename the `virtualenv/py2.7` as `env` through this issue.

**Comment by hsiaoyi0504** [comment]
Finished rebase for #151.

**Comment by childers** [comment]
@hsiaoyi0504 is this ready for review?

**Comment by hsiaoyi0504** [comment]
@childers Although it's ready for review, it seems to me that we want to put this later because it would cause many trouble if we didn't correctly update all the configuration on servers. Except that, I need to rebase again.

**Comment by g8tor** [comment]
Close #129 because ithas been handled in the g8tor/upgrades branch

**Pull request closed without merging**
